repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: kafka
    chart: bitnami/kafka
    installed: true
    values:
      - controller:
          replicaCount: 1
        externalAccess:
          enabled: true
          service:
            controller:
              containerPorts:
                external: 9094
              type: LoadBalancer
            broker:
              ports:
                external: 9094
              type: LoadBalancer
          autoDiscovery:
            enabled: true
        serviceAccount:
          create: true
        rbac:
          create: true
        sasl:
          interbroker:
            password: '{{ requiredEnv "INTERBROKER_PASSWORD" }}'
          controller:
            password: '{{ requiredEnv "CONTROLLER_PASSWORD" }}'
        kraft:
          clusterId: '{{ requiredEnv "KRAFT_CLUSTER_ID" }}'
  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    installed: false
    values:
      - defaultBackend:
          enabled: false
        controller:
          ingressClassResource:
            default: true
          service:
            omitClusterIP: true
        tcp:
          "9092": "default/kafka:9092"
  - name: consumer
    chart: ../consumer
    values:
      - image:
          tag: '{{ requiredEnv "IMAGE_TAG" }}'
          registry:
            username: '{{ requiredEnv "DOCKER_USERNAME" }}'
            password: '{{ requiredEnv "DOCKER_PASSWORD" }}'
