name: Build and Push to GHCR

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/consumer/**"
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}/consumer
          tags: |
            type=sha,prefix=commit,length=7

      - name: Build and push to GHCR
        uses: docker/build-push-action@v2
        with:
          context: packages/consumer
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      # - name: Build and push to GHCR
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: packages/consumer
      #     file: ./Dockerfile
      #     push: true
      #     tags: ghcr.io/${{ github.repository }}/consumer:latest

    # - name: Helm Deploy
    #   uses: deliverybot/helm@v1
    #   with:
    #     release: your-release
    #     namespace: your-namespace
    #     chart: ./helm-chart
    #     values: ./helm-chart/values.yaml
    #     token: ${{ secrets.KUBE_TOKEN }}
